# Use root/mysql as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    # restart: no
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - common-net
    

  adminer:
    image: adminer
    # restart: no
    ports:
      - 28080:8080
    networks:
      - common-net

networks:
  common-net:
    external: true 