GET /get HTTP/1.1
Host: 127.0.0.1:9999

###
GET http://127.0.0.1:9999/delay/3 HTTP/1.1
Host: www.hystrix.com

###
GET /actuator HTTP/1.1
Host: 127.0.0.1:9999

###
GET /actuator/beans HTTP/1.1
Host: 127.0.0.1:9999

###
GET /actuator/gateway/routes HTTP/1.1
Host: 127.0.0.1:9999

###
GET /actuator/gateway/globalfilters HTTP/1.1
Host: 127.0.0.1:9999

###
GET /actuator/gateway/routefilters HTTP/1.1
Host: 127.0.0.1:9999

###
POST /actuator/gateway/refresh HTTP/1.1
Host: 127.0.0.1:9999

###
GET /actuator/gateway/routes HTTP/1.1
Host: 127.0.0.1:9999

